version: "3.9"

services:

  postgres:
    image: postgres
    container_name: introducao_docker_db
    env_file: .env
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: nest-api-docker
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${ENV_PORT}:${ENV_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTEINER}
      PORT: ${ENV_PORT}
    command: >
      sh -c "until npx prisma migrate deploy; do echo 'Aguardando o banco ficar pronto...'; sleep 2; done && npm run start:prod"
